version: "3.3"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./db/prod:/data/db
  tsmongoauth-app:
    container_name: tsmongoauth-app
    build: 
      context: .
      dockerfile: ./docker/prod/api.dockerfile
    restart: always
    depends_on:
      - mongodb
    ports:
      - 5555:5555
      - 5173:5173
      - 3000:3000
    volumes:
      - ./:/app
    environment:
      - LOL=LOL